# Generated by Django 5.1.4 on 2026-08-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('rodadas_disputadas', models.PositiveSmallIntegerField()),
                ('n_simulacoes', models.PositiveIntegerField()),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('resultado', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-criada_em'],
                'get_latest_by': 'criada_em',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=5)),
                ('escudo_url', models.URLField(blank=True)),
                ('id_externo', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(unique=True)),
                ('rodada', models.PositiveSmallIntegerField()),
                ('gols_mandante', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gols_visitante', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='campeonato.time')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='campeonato.time')),
            ],
            options={
                'ordering': ['rodada', 'data'],
                'indexes': [models.Index(fields=['encerrada'], name='campeonato__encerra_a6e4ae_idx')],
            },
        ),
    ]
